name: Craftedbans
version: 1.1.2
author: buildcarter8
main: me.Tyler.craftedbans.Craftedbans
description: >
              Ban People :O
commands:
     ban:
       description: Ban a player
     kick:
       description: kick a player.
     unban:
        description: unban a player
     warn:
       description: CraftedSmart command- warn a player.
        
